# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [191]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([0, 1, 2, 3, 4, 5])
print(arr1[0:6], '\n')

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17]])
print(arr2[0:6, 1:6], '\n')
# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17]])
print(arr3)

[0 1 2 3 4 5] 

[[ 7  8  9 10 11]
 [13 14 15 16 17]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [192]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(arr1.shape, '\n')
print(arr1.ndim, '\n')
print(arr1.dtype, '\n')
print(arr1.size)

(6,) 

1 

int64 

6


In [190]:
# Attributes of 2-dimensional array
print(arr2.shape, '\n')
print(arr2.ndim, '\n')
print(arr2.dtype, '\n')
print(arr2.size)

(2, 6) 

2 

int64 

12


In [189]:
# Attributes of 3-dimensional array
print(arr3.shape, '\n')
print(arr3.ndim, '\n')
print(arr3.dtype, '\n')
print(arr3.size)

(3, 6) 

2 

int64 

18


In [29]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [180]:
# Create an array of shape (10, 2) with only ones
arr4 = np.ones((10, 2))
df = pd.DataFrame(arr4, columns = ['firstCol','secondCol'])
print(df)

   firstCol  secondCol
0       1.0        1.0
1       1.0        1.0
2       1.0        1.0
3       1.0        1.0
4       1.0        1.0
5       1.0        1.0
6       1.0        1.0
7       1.0        1.0
8       1.0        1.0
9       1.0        1.0


In [134]:
# Create an array of shape (7, 2, 3) of only zeros
arr5 = np.zeros((7, 2, 3))
print(arr5)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [135]:
# Create an array within a range of 0 and 100 with step 3
arr6 = np.array(range(0, 101))
print(arr6)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [136]:
# Create a random array with numbers between 0 and 10 of size (7, 2) 
randomArray1 = np.random.randint(0, 11, size=(7, 2))
print(randomArray1)

[[ 0  7]
 [ 0 10]
 [ 0  1]
 [ 1  5]
 [ 6  4]
 [ 0  0]
 [ 2  1]]


In [137]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomArray2 = np.random.random((3, 5))
print(randomArray2)

[[0.53093458 0.44778316 0.55289309 0.59269672 0.08085333]
 [0.36965446 0.24215994 0.80313976 0.47030063 0.98342314]
 [0.39882444 0.81643187 0.79834512 0.15071754 0.50819878]]


In [188]:
# Set the random seed to 42

np.random.seed(42)
print(randomArray2, '\n')
# Create a random array of numbers between 0 & 10 of size (4, 6)
randomArray3 = np.random.randint(0, 11, size=(4, 6))
print(randomArray3)

# the same each time running the code.
# The seed keeep the numbers the same each time you run the code

[[0.53093458 0.44778316 0.55289309 0.59269672 0.08085333]
 [0.36965446 0.24215994 0.80313976 0.47030063 0.98342314]
 [0.39882444 0.81643187 0.79834512 0.15071754 0.50819878]] 

[[ 6  3 10  7  4  6]
 [ 9  2  6 10 10  7]
 [ 4  3  7  7  2  5]
 [ 4  1  7  5  1  4]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [187]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomArray4 = np.random.randint(1, 11, size=(3, 7))
print(randomArray4, '\n')

# Find the unique numbers in the array you just created
uniqueNumbers = np.unique(randomArray4)

print(uniqueNumbers)

[[ 7  1  1  9  9  4  9]
 [ 3  7  6  8  9  5  1]
 [ 3 10  8  6  8  9  4]] 

[ 1  3  4  5  6  7  8  9 10]


In [140]:
# Find the 0'th index of the latest array you created
elementAtZeroIndex = randomArray4[0, 0]

print(elementAtZeroIndex)

1


In [141]:
# Get the first 2 rows of latest array you created
firstTwoRows = randomArray4[:2, :]
print(firstTwoRows)

[[ 1 10  6  9  1 10  3]
 [ 7  4  9  3  5  3  7]]


In [142]:
# Get the first 2 values of the first 2 rows of the latest array
firstTwoValues = randomArray4[:2, :2]
print(firstTwoValues)

[[ 1 10]
 [ 7  4]]


In [186]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

randomArray = np.random.randint(0, 11, size=(3, 5))
onesArray = np.ones((3, 5))
print('Random array = \n', randomArray)
print('\n Ones array = \n', onesArray)

Random array = 
 [[ 3  6 10  2  5]
 [ 1  9  8  4  5]
 [ 3 10  9  6  8]]

 Ones array = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [144]:
# Add the two arrays together
resultArray = randomArray + onesArray
print('Result Array = \n', resultArray)

Result Array = 
 [[10.  9. 10.  5.  2.]
 [ 4.  7.  8.  3.  1.]
 [ 4.  2.  8.  4.  2.]]


In [155]:
# Create another array of ones of shape (5, 3)
OnesArray2 = np.ones((5, 3))
print(OnesArray2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [156]:
# Try add the array of ones and the other most recent array together
# lastArrayInv = anotherOnesArray ** -1
transpose = np.transpose(OnesArray2)
RecentTwoArrays = transpose + resultArray
print(RecentTwoArrays)
# The result array is (3, 5) and the ones array was (5, 3)
# both have to be the SAME
# so I used the transpose to solve the error

[[11. 10. 11.  6.  3.]
 [ 5.  8.  9.  4.  2.]
 [ 5.  3.  9.  5.  3.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [157]:
# Create another array of ones of shape (3, 5)
OnesArray3 = np.ones((5, 3))
print(OnesArray3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [158]:
# Subtract the new array of ones from the other most recent array
recent2 = RecentTwoArrays
transpose2 = np.transpose(OnesArray3)
recent3 = recent2 - transpose2 
print(recent3)

[[10.  9. 10.  5.  2.]
 [ 4.  7.  8.  3.  1.]
 [ 4.  2.  8.  4.  2.]]


In [160]:
# Multiply the ones array with the latest array
Multiplication = transpose2 * recent3
print(Multiplication)

[[10.  9. 10.  5.  2.]
 [ 4.  7.  8.  3.  1.]
 [ 4.  2.  8.  4.  2.]]


In [161]:
# Take the latest array to the power of 2 using '**'
power = Multiplication ** 2
print(power)

[[100.  81. 100.  25.   4.]
 [ 16.  49.  64.   9.   1.]
 [ 16.   4.  64.  16.   4.]]


In [169]:
# Do the same thing with np.square()
power2 = np.square(Multiplication)
print(power2)

[[100.  81. 100.  25.   4.]
 [ 16.  49.  64.   9.   1.]
 [ 16.   4.  64.  16.   4.]]


In [170]:
# Find the mean of the latest array using np.mean()
mean1 = np.mean(power2)
print(mean1)

36.86666666666667


In [172]:
# Find the maximum of the latest array using np.max()
max1 = np.max(power2)
print(max1)

100.0


In [173]:
# Find the minimum of the latest array using np.min()
min1 = np.min(power2)
print(min1)

1.0


In [174]:
# Find the standard deviation of the latest array
standarDev = np.std(power2)
print(standarDev)

34.91869922485022


In [175]:
# Find the variance of the latest array
variance = np.var(power2)

print(variance)

1219.3155555555554


In [178]:
# Reshape the latest array to (3, 5, 1)
reshapedArray = power2.reshape(3, 5, 1)
print(reshapedArray)

[[[100.]
  [ 81.]
  [100.]
  [ 25.]
  [  4.]]

 [[ 16.]
  [ 49.]
  [ 64.]
  [  9.]
  [  1.]]

 [[ 16.]
  [  4.]
  [ 64.]
  [ 16.]
  [  4.]]]


In [179]:
# Transpose the latest array
transpose3 = np.transpose(reshapedArray)
print(transpose3)
# the raw becomes column and vice vesrsa

[[[100.  16.  16.]
  [ 81.  49.   4.]
  [100.  64.  64.]
  [ 25.   9.  16.]
  [  4.   1.   4.]]]


What does the transpose do?

In [181]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0, 11, size=(3, 3))
array2 = np.random.randint(0, 11, size=(3, 2))
print(array1, '\n')
print(array2)

[[5 5 9]
 [3 5 1]
 [9 1 9]]
[[3 7]
 [6 8]
 [7 4]]


In [182]:
# Perform a dot product on the two newest arrays you created
dotProduct = np.dot(array1, array2)
print(dotProduct)

[[108 111]
 [ 46  65]
 [ 96 107]]


In [196]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3 = np.random.randint(0, 11, size=(4, 3))
array4 = np.random.randint(0, 11, size=(4, 3))
print(array3, '\n')
print(array4)

[[8 9 4]
 [1 3 6]
 [7 2 0]
 [3 1 7]] 

[[3 1 5]
 [5 9 3]
 [5 1 9]
 [1 9 3]]


In [198]:
# Perform a dot product on the two newest arrays you created
dotProduct2 = np.dot(array3.flatten(), array4.flatten())
print(dotProduct2)
# I searched and found that the flatten() solve the problem 
# return a copy of a given array in such a way that it is collapsed into one dimension

173


It doesn't work. How would you fix it?

In [202]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transaArray3 = np.transpose(array3)
dotProduct3 = np.dot(transaArray3, array4)
dotProduct4 = np.dot(transaArray3, array3)
print(dotProduct3, '\n')
print(dotProduct4)

[[ 67  51 115]
 [ 53  47  75]
 [ 49 121  59]] 

[[123  92  59]
 [ 92  95  61]
 [ 59  61 101]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [219]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
randArray1 = np.random.randint(0, 11, size=(3, 3))
randArray2 = np.random.randint(0, 11, size=(3, 3))
print(randArray1, '\n')
print(randArray2)

[[ 8  2  6]
 [ 5  7 10]
 [ 8  4  0]] 

[[ 2  9  7]
 [10  5  7]
 [ 8  3  0]]


In [208]:
# Compare the two arrays with '>'
comparison = randArray1 > randArray2
print(comparison)
# it compares if the result true or false not the value itself 

[[False  True  True]
 [ True  True  True]
 [ True False  True]]


What happens when you compare the arrays with `>`?

In [206]:
# Compare the two arrays with '>='
comparison2 = randArray1 >= randArray2
print(comparison2)

[[ True  True False]
 [False False False]
 [False False  True]]


In [211]:
# Find which elements of the first array are greater than 7
greaterThan7 = randArray1 > 7
print(greaterThan7)

[[False  True  True]
 [ True  True False]
 [False False False]]


In [212]:
# Which parts of each array are equal? (try using '==')
equalParts = randArray1 == randArray2
print(equalParts)

[[False False False]
 [False False False]
 [ True False False]]


In [43]:
# Sort one of the arrays you just created in ascending order


In [213]:
# Sort the indexes of one of the arrays you just created
sortedArray = np.sort(randArray1, axis=None)
sortedArray = sortedArray.reshape(randArray1.shape)
print(sortedArray)

[[ 0  2  3]
 [ 6  6  8]
 [ 9  9 10]]


In [216]:
# Find the index with the maximum value in one of the arrays you've created
maxIndex = np.argmax(randArray1)
# max_index_row = max_index // randArray1.shape[1]  # row index
# max_index_col = max_index % randArray1.shape[1]   # column index
print(maxIndex)

7


In [217]:
# Find the index with the minimum value in one of the arrays you've created
minIndex = np.argmin(randArray1)
print(minIndex)

1


In [220]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
maxIndices = np.argmax(randArray1, axis=1)
print(maxIndices)

[0 2 0]


In [221]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
minIndices = np.argmin(randArray1, axis=1)
print(minIndices)

[1 0 2]


In [222]:
# Create an array of normally distributed random numbers
mean = 0
stdDev = 1
arraySize = 10
randomArray = np.random.normal(mean, stdDev, arraySize)
print(randomArray)

[-0.01548334 -0.02737645  0.81787351 -1.05460447 -0.75832712  0.45741565
 -0.06437805  0.34490234 -0.08008734 -0.24138013]


In [223]:
# Create an array with 10 evenly spaced numbers between 1 and 100
numbers = np.linspace(1, 100, 10)
print(numbers)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.